services:
  nexusmods_monitor_metadata:
    image: ${DOCKER_REGISTRY-}nexusmods_monitor_metadata:${TAG-latest}
    environment:
      ASPNETCORE_URLS: "http://*:80"
      ConnectionStrings__Cache: Host=host.docker.internal;Port=19002;Database=nexusmodsmonitor;Username=nexusmodsmonitor;Password=nexusmodsmonitor;Include Error Detail=true;
    build:
      context: ../../.
      dockerfile: src/NexusMods.Monitor.Metadata.API/Dockerfile
    depends_on:
      - metadata_postgres
    ports:
      - "19001:80"
    networks:
      - internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: 'curl -H "X-Correlation-ID: 00000000-0000-0000-0000-000000000000" --fail http://localhost || exit 1'
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  metadata_postgres:
    image: postgres:15-alpine
    environment:
     POSTGRES_USER: nexusmodsmonitor
     POSTGRES_PASSWORD: nexusmodsmonitor
    volumes:
      - ./metadata_postgres:/var/lib/postgresql/data
    ports:
      - "19002:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U nexusmodsmonitor -d nexusmodsmonitor'"]
      interval: 30s
      timeout: 60s
      retries: 5