version: '3.8'
services:
  nexusmods.monitor.bot.discord:
    environment:
      Discord__BotToken: PLACEHOLDER

  nexusmods.monitor.bot.slack:
    environment:
      Slack__BotToken: PLACEHOLDER

  nexusmods.monitor.scraper:
    environment:
      NexusMods__APIKey: PLACEHOLDER
