version: '3.8'

volumes:
  postgresql_data: { }

networks:
  internal:
  eventbus:
  database:

services:
  nexusmods_monitor_bot_discord:
    image: ${DOCKER_REGISTRY-}nexusmods_monitor_bot_discord
    environment:
      Discord__BotToken: PLACEHOLDER
      MetadataAPI__APIEndpointV1: http://nexusmods_monitor_metadata/api/v1/metadata/
      SubscriptionsAPI__APIEndpointV1: http://nexusmods_monitor_subscriptions/api/v1/subscriptions/
      EventBus__Servers__0: nats://nats:4222
    build:
      context: ../../.
      dockerfile: src/NexusMods.Monitor.Bot.Discord.Host/Dockerfile
    depends_on:
      - nexusmods_monitor_subscriptions
      - nexusmods_monitor_scraper
      - nats
    networks:
      - internal
      - eventbus

  nexusmods_monitor_bot_slack:
    image: ${DOCKER_REGISTRY-}nexusmods_monitor_bot_slack
    environment:
      Slack__BotToken: PLACEHOLDER
      MetadataAPI__APIEndpointV1: http://nexusmods_monitor_metadata/api/v1/metadata/
      SubscriptionsAPI__APIEndpointV1: http://nexusmods_monitor_subscriptions/api/v1/subscriptions/
      EventBus__Servers__0: nats://nats:4222
    build:
      context: ../../.
      dockerfile: src/NexusMods.Monitor.Bot.Slack.Host/Dockerfile
    depends_on:
      - nexusmods_monitor_subscriptions
      - nexusmods_monitor_scraper
      - nats
    networks:
      - internal
      - eventbus

  nexusmods_monitor_scraper:
    image: ${DOCKER_REGISTRY-}nexusmods_monitor_scraper
    environment:
      MetadataAPI__APIEndpointV1: http://nexusmods_monitor_metadata/api/v1/metadata/
      SubscriptionsAPI__APIEndpointV1: http://nexusmods_monitor_subscriptions/api/v1/subscriptions/
      EventBus__Servers__0: nats://nats:4222
      ConnectionStrings__NexusMods: Host=postgres;Port=5432;Database=nexusmods;Username=nexusmodsmonitor;Password=nexusmodsmonitor;Include Error Detail=true;
    build:
      context: ../../.
      dockerfile: src/NexusMods.Monitor.Scraper.Host/Dockerfile
    depends_on:
      - nexusmods_monitor_subscriptions
      - postgres
      - nats
    networks:
      - internal
      - eventbus
      - database

  nexusmods_monitor_metadata:
    image: ${DOCKER_REGISTRY-}nexusmods_monitor_metadata
    environment:
      NexusMods__APIKey: PLACEHOLDER
      NexusMods__APIEndpoint: https://api.nexusmods.com/
      NexusMods__Endpoint: https://www.nexusmods.com/
      ASPNETCORE_URLS: "http://*:80"
    build:
      context: ../../.
      dockerfile: src/NexusMods.Monitor.Metadata.API/Dockerfile
    networks:
      - internal

  nexusmods_monitor_subscriptions:
    image: ${DOCKER_REGISTRY-}nexusmods_monitor_subscriptions
    environment:
      MetadataAPI__APIEndpointV1: http://nexusmods_monitor_metadata/api/v1/metadata/
      ConnectionStrings__Subscriptions: Host=postgres;Port=5432;Database=subscriptions;Username=nexusmodsmonitor;Password=nexusmodsmonitor;Include Error Detail=true;
      ASPNETCORE_URLS: "http://*:80"
    build:
      context: ../../.
      dockerfile: src/NexusMods.Monitor.Subscriptions.API/Dockerfile
    depends_on:
      - postgres
    networks:
      - internal
      - database


  nats:
    image: nats:alpine
    #command: "--syslog --remote_syslog udp://seq_syslog:1514"
    ports:
      - 34222:4222
      - 36222:6222
      - 38222:8222
    depends_on:
      - graylog
    networks:
      - eventbus
      - logging


  postgres:
    image: postgres:alpine
    environment:
     POSTGRES_USER: nexusmodsmonitor
     POSTGRES_PASSWORD: nexusmodsmonitor
    volumes:
      - postgresql_data:/var/lib/postgresql
    ports:
      - 35432:5432
    networks:
      - database
