version: '3.8'

volumes:
  seq_data: { }

networks:
  logging:
  logging_internal:

services:
  nexusmods_monitor_bot_discord:
    environment:
      Serilog__WriteTo__2__Args__serverUrl: http://seq:5341
    depends_on:
      - seq
    networks:
      - logging

  nexusmods_monitor_bot_slack:
    environment:
      Serilog__WriteTo__2__Args__serverUrl: http://seq:5341
    depends_on:
      - seq
    networks:
      - logging

  nexusmods_monitor_scraper:
    environment:
      Serilog__WriteTo__2__Args__serverUrl: http://seq:5341
    depends_on:
      - seq
    networks:
      - logging

  nexusmods_monitor_metadata:
    environment:
      Serilog__WriteTo__2__Args__serverUrl: http://seq:5341
    depends_on:
      - seq
    networks:
      - logging

  nexusmods_monitor_subscriptions:
    environment:
      Serilog__WriteTo__2__Args__serverUrl: http://seq:5341
    depends_on:
      - seq
    networks:
      - logging


  seq:
    image: datalust/seq:latest
    ports:
      - 30080:80
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data
    networks:
      - logging
      - logging_internal
