volumes:
  seq_data: { }

services:
  nexusmods_monitor_bot_discord:
    environment:
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__serverUrl: http://host.docker.internal:19060
    depends_on:
      - seq
    networks:
      - logging

  nexusmods_monitor_scraper:
    environment:
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__serverUrl: http://host.docker.internal:19060
    depends_on:
      - seq
    networks:
      - logging

  nexusmods_monitor_metadata:
    environment:
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__serverUrl: http://host.docker.internal:19060
    depends_on:
      - seq
    networks:
      - logging

  nexusmods_monitor_subscriptions:
    environment:
      Serilog__WriteTo__1__Name: Seq
      Serilog__WriteTo__1__Args__serverUrl: http://host.docker.internal:19060
    depends_on:
      - seq
    networks:
      - logging

  seq:
    image: datalust/seq:latest
    ports:
      - "19060:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data
    networks:
      - logging